server:
  port: 8989
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      routes:
        - id: cliente-service
          uri: ${CLIENTE_SERVICE_URL:http://localhost:8000}
          predicates:
            - Path=/cliente/**

        - id: cuentas-service
          uri: ${CUENTAS_SERVICE_URL:http://localhost:9000}
          predicates:
            - Path=/cuentas/**
        - id: movimientos-service
          uri: ${MOVIMIENTOS_SERVICE_URL:http://localhost:9000}
          predicates:
            - Path=/movimientos/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

  mvc:
    problemdetails:
      enabled: true

springdoc:
  swagger-ui:
    use-root-path: true
    springdoc:
      swagger-ui:
        use-root-path: true
