server:
  port: 9000
spring:
  application:
    name: cuentas
  datasource:
    url: jdbc:postgresql://localhost:5432/cuentas
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true