server:
  port: 9000
spring:
  application:
    name: cuentas
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:35432/cuentas}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true