name: 'sistema_microservicios'
services:
  cliente-db:
    image: postgres:16-alpine
    container_name: cliente-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=clientes
    ports:
      - "25432:5432"
    deploy:
      resources:
        limits:
          memory: 500m

  cliente-rabbitmq:
    image: rabbitmq:3.12.11-management
    container_name: cliente-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m

  cuentas-db:
    image: postgres:16-alpine
    container_name: cuentas-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cuentas
    ports:
      - "35432:5432"
    deploy:
      resources:
        limits:
          memory: 500m

