server:
  port: 8000
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: cliente
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:25432/clientes}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true

clientes:
  publish-order-events-job-cron: 1 * * * * *
  clientes-events-exchange: cliente-exchange
  new-cliente-queue: cliente